"""add bot fields

Revision ID: 7b03e4b2bc12
Revises: b0cfafab680b
Create Date: 2026-05-11 15:32:31.565724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b03e4b2bc12'
down_revision: Union[str, Sequence[str], None] = 'b0cfafab680b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_leads_assigned_to_users', 'users', ['assigned_to'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_token', sa.String(length=64), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_users_invite_token'), ['invite_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_invite_token'))
        batch_op.drop_column('invite_token')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leads_assigned_to_users', type_='foreignkey')
        batch_op.alter_column('assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
