"""created_at + mapped cols

Revision ID: b0cfafab680b
Revises: 7265e0cf2de2
Create Date: 2026-04-24 15:05:39.980511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cfafab680b'
down_revision: Union[str, Sequence[str], None] = '7265e0cf2de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.drop_column('leads', 'created_at')
    # ### end Alembic commands ###
