"""add id field and invite token

Revision ID: ca0df5e1352b
Revises: 7b03e4b2bc12
Create Date: 2026-05-12 17:05:53.150700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0df5e1352b'
down_revision: Union[str, Sequence[str], None] = '7b03e4b2bc12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint('fk_leads_public_id', ['public_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leads_public_id', type_='unique')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
